### ISSUE TITLE
Very good idea, does it have the same function as stmview?

### ISSUE THREAD

**Issue by hongshui3000** [aq1018/cortex-debug-trace-decoder#1]
STMView:
https://github.com/klonyyy/STMViewer

**Comment by aq1018** [comment]
From the looks of it, STMViewer is a very powerful debug tool, where as this coretex-debu-trace-decoder is just a small decoder plugin for Cortex-Debug, which is itself a Visual Studio Code extension. So are you are comparing apples and oranges here.  

`coretex-debu-trace-decoder` only decodes binary data you send to RTT, SWO channels and sends it to Cortex-Debug to display graphs. The throughput is much much lower than using a SWO pin and STMViewer.
